name: rps-prod_${TAG:-latest}
services:
  nginx:
    image: RPS3/nginx:${TAG:-latest}
    build:
      context: .
      dockerfile: ./RPS3-Nginx/prod.Dockerfile
      args:
        VITE_HOST_URL: ${VITE_HOST_URL}
    container_name: prod-nginx
    environment:
      WDS_SOCKET_PORT: 0
      EMAIL_ADDRESS: /run/secrets/email_address
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot:/etc/letsencrypt
    secrets:
      - email_address
    networks:
      - public
    depends_on:
      - server

  server:
    image: RPS3/server:${TAG:-latest}
    build:
      context: .
      dockerfile: ./RPS3-Server/prod.Dockerfile
      args:
        NODE_ENV: production
    container_name: prod-server
    environment:
      VITE_HOST_URL: ${VITE_HOST_URL}
      JWT_ACCESS_TOKEN_SECRET: /run/secrets/jwt_access_token_secret
      JWT_REFRESH_TOKEN_SECRET: /run/secrets/jwt_refresh_token_secret
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - jwt_access_token_secret
      - jwt_refresh_token_secret
      - db_password
    networks:
      - public
    restart: always
    depends_on:
      db-prod:
        condition: service_healthy

  db-prod:
    image: mysql:8.0
    container_name: mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: database_production
      MYSQL_USER: produser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
    networks:
      - public
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_prod_data:
  certbot:

secrets:
  jwt_access_token_secret:
    file: ./secrets/jwt_access_token_secret.txt
  jwt_refresh_token_secret:
    file: ./secrets/jwt_refresh_token_secret.txt
  email_address:
    file: ./secrets/email.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt

networks:
  public:
